import React from 'react'

const SobreNosotrosPagina = () => {
  return (
    <div>
      <h2 className='text-3xl mb-10 px-2 py-10 font-bold'>Acerca de nosotros</h2>
      <img src="https://hips.hearstapps.com/hmg-prod/images/tiendas-ropa-mujer-madrid-645e038123d62.jpg" className='w-1/2 mx-auto' alt="" />
      <p className='mt-10 px-5 py-5'>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus sit est laudantium a enim distinctio facere hic officia? Necessitatibus dolorum commodi voluptate quisquam voluptatem nam tenetur dolorem aspernatur eum, rerum itaque dolores. Unde, eveniet? Sunt molestiae fugit nostrum quis libero dolore vel corporis reiciendis temporibus iure voluptate, in nisi natus dolores, obcaecati alias fugiat, minima sequi unde! Provident facilis a aliquam totam dicta sequi ratione ut unde harum velit suscipit saepe omnis praesentium fuga molestiae exercitationem nisi recusandae rerum, eaque doloremque facere quo culpa. Iusto praesentium et ea, consequatur dolores quis fuga iure eligendi est repellendus sequi porro magnam voluptas cupiditate! Tenetur, repellendus! Nihil deserunt magni dolorem iste perspiciatis possimus incidunt ex soluta officia est ab alias at facere cupiditate vitae quaerat ullam, quia dicta deleniti nisi et tenetur. Ipsa obcaecati impedit nemo, voluptatum ad perspiciatis dolores incidunt ea doloremque similique debitis iure ab sapiente nesciunt eaque harum commodi ex sunt. Eaque dicta perferendis omnis adipisci distinctio corrupti magnam fuga dolor voluptatibus laudantium ea provident dolores atque aspernatur possimus nam similique aliquam, eum amet ipsa sequi nostrum vero quaerat mollitia. Saepe asperiores aliquid, vel consequuntur commodi in error, perferendis veritatis est iste quidem. Exercitationem pariatur velit at consectetur! Tempora provident alias consectetur error similique reiciendis aut, voluptatibus repellat sunt cupiditate, maiores voluptas in quam nihil distinctio nulla quibusdam eius atque ducimus ex dolorum recusandae. Voluptate unde vitae quod velit nam quae doloremque quasi accusantium repellat sint est officia laborum, mollitia quo veniam? Numquam aliquam, libero ipsa labore magni, similique ad architecto fugiat eos ut ipsam. Ratione, ut odio illo facere animi inventore molestias maxime iste omnis cumque optio et tempora, temporibus quaerat error id reiciendis distinctio, quibusdam asperiores nostrum perspiciatis! Consequuntur, tenetur officia molestiae sapiente commodi maiores eaque quas esse? Ducimus, eveniet at molestiae dolor, ea praesentium deserunt saepe sunt consequatur ut ullam similique nobis tempora fugiat. Autem, ut laborum. Maxime eveniet quia illum. Natus sapiente voluptatem laborum minima labore quaerat debitis recusandae ea hic vitae sit neque quis animi placeat, vero ut ratione quo optio praesentium, cupiditate explicabo officiis. Iste debitis, quaerat ipsum totam, libero tempora non fugit esse ipsam atque neque numquam blanditiis excepturi asperiores deleniti voluptas praesentium itaque repudiandae! Voluptates et velit expedita enim maxime quae magni dolorum placeat, minima alias quisquam odit ea, impedit iusto veniam sint eius labore architecto debitis vero ut est sapiente consectetur. Distinctio beatae ipsa ab commodi veritatis possimus, atque libero eos?
      </p>
    </div>
  )
}

export default SobreNosotrosPagina
